"""empty message

Revision ID: 01db42935708
Revises: 65659267a70a
Create Date: 2024-11-21 14:54:06.718555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01db42935708'
down_revision = '65659267a70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependence',
    sa.Column('dependence_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('dependence_structure', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dependence_id')
    )
    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('goal_structure', sa.Text(), nullable=True))
        batch_op.drop_column('structure')
        batch_op.drop_column('create_time')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_root', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('root_goal_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('goals_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'goals', ['parent_goal_id'], ['goal_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'goals', ['root_goal_id'], ['goal_id'])
        batch_op.drop_column('template_id')

    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_structure', sa.Text(), nullable=True))
        batch_op.drop_column('structure')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('front_task_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('tasks_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('tasks_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('tasks_ibfk_6', type_='foreignkey')
        batch_op.drop_constraint('tasks_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['front_task_id'], ['task_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('template_id')
        batch_op.drop_column('assigned_to_user_id')
        batch_op.drop_column('assigned_to_team_id')
        batch_op.drop_column('depends_on_task_id')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depends_on_task_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assigned_to_team_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('assigned_to_user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tasks_ibfk_2', 'users', ['assigned_to_user_id'], ['user_id'])
        batch_op.create_foreign_key('tasks_ibfk_6', 'tasks', ['depends_on_task_id'], ['task_id'])
        batch_op.create_foreign_key('tasks_ibfk_3', 'teams', ['assigned_to_team_id'], ['team_id'])
        batch_op.create_foreign_key('tasks_ibfk_5', 'task_templates', ['template_id'], ['template_id'])
        batch_op.drop_column('front_task_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure', mysql.TEXT(), nullable=True))
        batch_op.drop_column('task_structure')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('goals_ibfk_2', 'goal_templates', ['template_id'], ['template_id'])
        batch_op.drop_column('root_goal_id')
        batch_op.drop_column('is_root')

    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('structure', mysql.TEXT(), nullable=True))
        batch_op.drop_column('goal_structure')
        batch_op.drop_column('created_time')

    op.drop_table('task_dependence')
    # ### end Alembic commands ###
