"""empty message

Revision ID: 0ae921a2d263
Revises: fafc9056a2d4
Create Date: 2024-11-20 16:08:29.891778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ae921a2d263'
down_revision = 'fafc9056a2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('structure', sa.Text(), nullable=True))
        batch_op.drop_constraint('task_templates_ibfk_2', type_='foreignkey')
        batch_op.drop_column('default_priority')
        batch_op.drop_column('default_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_priority', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('task_templates_ibfk_2', 'categories', ['default_category_id'], ['category_id'])
        batch_op.drop_column('structure')
        batch_op.drop_column('create_time')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
