"""empty message

Revision ID: 0f4fcda6ade5
Revises: 01db42935708
Create Date: 2024-11-21 15:23:02.170389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4fcda6ade5'
down_revision = '01db42935708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('goals_ibfk_5', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_foreign_key('goals_ibfk_5', 'goals', ['parent_goal_id'], ['goal_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
