"""empty message

Revision ID: 3d6f3206b01d
Revises: 0ae921a2d263
Create Date: 2024-11-20 18:23:53.274337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d6f3206b01d'
down_revision = '0ae921a2d263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_time', sa.Integer(), nullable=True))
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('pomodoro_sessions_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pomodoro_sessions_ibfk_1', 'users', ['user_id'], ['user_id'])
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('remaining_time')

    # ### end Alembic commands ###
