"""empty message

Revision ID: 65659267a70a
Revises: 3d6f3206b01d
Create Date: 2024-11-20 18:53:57.740144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65659267a70a'
down_revision = '3d6f3206b01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_stop', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoro_sessions', schema=None) as batch_op:
        batch_op.drop_column('is_stop')

    # ### end Alembic commands ###
