"""Initial migration.

Revision ID: e8dad5cef3ce
Revises: 
Create Date: 2024-11-19 14:34:05.987466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8dad5cef3ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structure', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_templates', schema=None) as batch_op:
        batch_op.drop_column('structure')

    # ### end Alembic commands ###
